apiVersion: v2
name: my-app
description: A Helm chart for my application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 16.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 20.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: loki
    version: 5.41.6
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
