apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
        - name: hermes
          image: "{{ .Values.image.hermes.repository }}:{{ .Values.image.hermes.tag }}"
          ports:
            - containerPort: 9900
          resources:
            requests:
              cpu: "2000m"
              memory: "2048Mi"
            limits:
              cpu: "3000m"
              memory: "4096Mi"
          env:
            - name: PORT
              value: "9900"
            - name: REDIS_URL
              value: {{ include "composio.redis.url" . }}
            - name: DATABASE_URL
              value: {{ include "composio.postgresql.url" . }}
            - name: LOKI_URL
              value: {{ .Values.loki.url }}
        - name: mercury
          image: "{{ .Values.image.mercury.repository }}:{{ .Values.image.mercury.tag }}"
          env:
            - name: PORT
              value: "8000"
            - name: REDIS_URL
              value: {{ include "composio.redis.url" . }}
            - name: DATABASE_URL
              value: {{ include "composio.postgresql.url" . }}
            - name: OPENAI_API_KEY
              value: "{{ .Values.openai.apiKey }}"
            - name: BACKEND_URL
              value: "http://hermes:9900"
            - name: FRONTEND_URL
              value: "https://app.{{ .Values.ingress.host }}"
            - name: MERCURY_OPENAPI_SERVER
              value: "http://mercury-openapi:8100"
            - name: LOKI_URL
              value: {{ .Values.loki.url }}
          resources:
            requests:
              cpu: "2000m"
              memory: "2048Mi"
            limits:
              cpu: "3000m"
              memory: "4096Mi"
        - name: mercury-openapi
          image: "{{ .Values.image.mercuryOpenapi.repository }}:{{ .Values.image.mercuryOpenapi.tag }}"
          env:
            - name: PORT
              value: "8100"
            - name: REDIS_URL
              value: {{ include "composio.redis.url" . }}
            - name: DATABASE_URL
              value: {{ include "composio.postgresql.url" . }}
            - name: OPENAI_API_KEY
              value: "{{ .Values.openai.apiKey }}"
            - name: BACKEND_URL
              value: "http://hermes:9900"
            - name: LOKI_URL
              value: {{ .Values.loki.url }}
          resources:
            requests:
              cpu: "2000m"
              memory: "2048Mi"
            limits:
              cpu: "3000m"
              memory: "4096Mi"
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NEXT_PUBLIC_API_URL
              value: "https://backend.{{ .Values.ingress.host }}"
            - name: BACKEND_URL
              value: "https://backend.{{ .Values.ingress.host }}"
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
